stages:
  - build
  - deploy

variables:
  IMAGE_NAME: registry.gitlab.com/sumitrai2609/NIKE

# 1️⃣ Build Docker image and push to GitLab Registry
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHA .
    - docker push $IMAGE_NAME:$CI_COMMIT_SHA
  only:
    - main

# 2️⃣ Deploy (optional: to your own server)
deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh
  script:
    - ssh -o StrictHostKeyChecking=no user@your-server "
        docker login -u '$CI_REGISTRY_USER' -p '$CI_REGISTRY_PASSWORD' $CI_REGISTRY &&
        docker pull $IMAGE_NAME:$CI_COMMIT_SHA &&
        docker stop nike-site || true &&
        docker rm nike-site || true &&
        docker run -d -p 80:80 --name nike-site $IMAGE_NAME:$CI_COMMIT_SHA
      "
  only:
    - main

